steps:
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: bash
  args:
    - -c
    - |
      echo "List repository"
      ls -la
      echo "Install functions dependencies"
      cd functions
      npm ci

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - -c
    - |
      echo "Authenticate gcloud using service account key file"
      gcloud auth activate-service-account --key-file=${_SERVICE_ACCOUNT_KEY_PATH}
      gcloud config set project $PROJECT_ID
      echo "Install firebase-tools"
      npm install -g firebase-tools
      echo "Deploy functions and hosting"
      firebase deploy --only functions,hosting --project $PROJECT_ID
secrets:
- kmsKeyName: ${_KMS_KEY_NAME}
  secretEnv:
    SERVICE_ACCOUNT_JSON: ${_SECRET_NAME}
substitutions:
  _SERVICE_ACCOUNT_KEY_PATH: '/workspace/service-account.json'
  _SECRET_NAME: 'projects/$PROJECT_ID/secrets/firebase-sa/versions/latest'
  _KMS_KEY_NAME: '' 
timeout: '1200s'

