name: Deploy Firebase Functions

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install function dependencies
        working-directory: functions
        run: npm ci --legacy-peer-deps

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Deploy functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only functions --token "$FIREBASE_TOKEN"
